name: deploytest
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x gradlew
          gradle wrapper
          ./gradlew build
      - name: Test application
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build
