name: deploytest
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: setup gradle
        uses: gradle/gradle-build-action@v2
      - name: cache dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x gradlew
          gradle wrapper
          ./gradlew build
      - name: get the fileName
        id: publish
        run: find src/main/java/com/argosinfo/argosinfosystem/*.java -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Test application
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build
  second-job:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: cache dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x gradlew
          gradle wrapper
          ./gradlew build
      - name: get the output value
        run: echo "${{ needs.firstjob.outputs.script-file }}"
