name: deploytest
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: build the code
        uses: skx/github-action-build@master
        with:
          builder: .github/build
  
